"""init

Revision ID: 2fbd495d3bfd
Revises: 
Create Date: 2020-09-14 16:53:00.092504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbd495d3bfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.Text(length=131072), nullable=True),
    sa.Column('about', sa.Text(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateur_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_utilisateur_nom'), ['nom'], unique=True)

    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=128), nullable=True),
    sa.Column('creation', sa.DateTime(), nullable=True),
    sa.Column('id_auteur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_auteur'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_creation'), ['creation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_creation'))

    op.drop_table('publication')
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateur_nom'))
        batch_op.drop_index(batch_op.f('ix_utilisateur_email'))

    op.drop_table('utilisateur')
    # ### end Alembic commands ###
