"""Last Online field

Revision ID: 7470a9344b6e
Revises: 2fbd495d3bfd
Create Date: 2020-09-24 08:50:24.249547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7470a9344b6e'
down_revision = '2fbd495d3bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastonline', sa.DateTime(), nullable=True))
    print('a')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('lastonline')

    # ### end Alembic commands ###
