"""partisans

Revision ID: d4e103c6035f
Revises: 7470a9344b6e
Create Date: 2020-10-05 15:34:08.837501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e103c6035f'
down_revision = '7470a9344b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBPartisans',
    sa.Column('suiveur', sa.Integer(), nullable=True),
    sa.Column('suivit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suiveur'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['suivit'], ['utilisateur.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partisans')
    print('b')
    # ### end Alembic commands ###
